### PR TITLE
Ported trakt api class to trakt api v2

### PR DESCRIPTION
**Pull request by Razzeee**
I've ported the Trakt class to api v2.

- I've left the api key empty, as you would probably like to provide it. See line 4.
- I've tested the calls via keyboard shortcuts, but I don't have a clue how I get real frontends. So all I've checked is that it's not causing any script errors.

So you should really test this before accepting the pull request or let me know how I can test it.

### CODE REVIEW

**Comment by phil65** [comment]
Thanks. Could you rebase? Cannot merge it, seems to have some conflicts.

**Comment by Razzeee** [comment]
So I've rebased, let me know if this works.

**Comment by phil65** [comment]
uhhh that totally messed it up :)
you attached a whole lot of my commits to this PR and it still says "We can’t automatically merge this pull request. "
If you dont want to mess around with that anymore then I could cherry-pick your change and solve the conflicts myself. Or do you want to give it another try? :)

**Comment by Razzeee** [comment]
Well I'm not sure how. I usually do prs for this case, but that will add a pr merged commit to the log. 
And I wanted to do it right this time :/

**Pull request closed without merging**
